#!/bin/sh

#-------------------------------------------------------------------------------
# Set default values for compilation
#-------------------------------------------------------------------------------
: ${nb_fc:="mpixlf77"}
: ${nb_cc:="mpixlc"}
: ${nb_fflags:="-qsuppress=cmpmsg"}
: ${nb_cflags:=}
: ${nb_usr_lflags:=}

#-------------------------------------------------------------------------------
# Submission parameters
#-------------------------------------------------------------------------------
: ${nb_np:=32}
: ${nb_ppn:=32}
: ${nb_project:=ATPESC2017}
: ${nb_queue:=default}
: ${nb_time:=60}

#-------------------------------------------------------------------------------
# Build the submit command for the machine
#-------------------------------------------------------------------------------
function bgq_submit() {
  local nb_casename=$1
  local nb_tag=$2
  local nb_np=$3
  local nb_ppn=$4

  local nb_nnodes=$(( nb_np/nb_ppn ))
  local NB_SUBMIT_CMD=""

  if [ $nb_nnodes = 0 ]; then
    NB_SUBMIT_CMD=":"
  else
    NB_SUBMIT_CMD="qsub -n $nb_nnodes
                     -q $nb_queue
                     -t $nb_time
                     -A $nb_project
                     --mode script"
  fi

  ${NB_SUBMIT_CMD} ${NB_JOBS_DIR}/${nb_machine}.submit $1 $2 $3 $4
}
