#!/bin/sh

# Machine: BG/Q
# Variables referenced from outside: $nb_np

nb_arg3=
nb_rpn=32
nb_project=ATPESC2017
nb_queue=default
nb_time=60

nb_nnodes=$(( nb_np/nb_rpn ))

if [ $nb_nnodes = 0 ]; then
  NB_RUN_CMD=":"
else
  NB_RUN_CMD="qsub -n $nb_nnodes
                   -q $nb_queue
                   -t $nb_time
                   -A $nb_project
                   --mode script"
fi
