#!/bin/sh

#-------------------------------------------------------------------------------
# Set default values for compilation
#-------------------------------------------------------------------------------
: ${nb_fc:="ftn"}
: ${nb_cc:="cc"}
: ${nb_fflags:=}
: ${nb_cflags:=}
: ${nb_usr_lflags:=}

#-------------------------------------------------------------------------------
# Submission parameters
#-------------------------------------------------------------------------------
: ${nb_np:=64}
: ${nb_ppn:=64}
: ${nb_partition:="regular"}
: ${nb_time:=60}

#-------------------------------------------------------------------------------
# Build the submit command for the machine
#-------------------------------------------------------------------------------
function knl_cori_submit() {
  local nb_casename=$1
  local nb_tag=$2
  local nb_np=$3
  local nb_ppn=$4

  local nb_nnodes=$(( nb_np/nb_ppn ))
  local NB_SUBMIT_CMD=""

  if [ $nb_nnodes = 0 ]; then
    NB_SUBMIT_CMD=":"
  else
    NB_SUBMIT_CMD="sbatch -N $nb_nnodes
                       -C knl,cache,flat
                       -p $nb_partition
                       -t $nb_time"
  fi

  ${NB_SUBMIT_CMD} ${NB_JOBS_DIR}/${nb_machine}.submit $1 $2 $3 $4
}
