#!/bin/sh

#-------------------------------------------------------------------------------
# Set default values for compilation
#-------------------------------------------------------------------------------
: ${nb_fc:="ftn"}
: ${nb_cc:="cc"}
: ${nb_fflags:=}
: ${nb_cflags:=}
: ${nb_usr_lflags:=}

#-------------------------------------------------------------------------------
# Submission parameters
#-------------------------------------------------------------------------------
: ${nb_np:=64}
: ${nb_ppn:=64}
: ${nb_project:="GasJetsCylPrio_tesp"}
: ${nb_queue:="default"}
: ${nb_time:=60}

#-------------------------------------------------------------------------------
# Build the run command for the machine
#-------------------------------------------------------------------------------
nb_nnodes=$(( nb_np/nb_ppn ))
if [ $nb_nnodes -le 4 ]; then
  nb_queue=debug-flat-quad
fi

if [ $nb_nnodes = 0 ]; then
  NB_RUN_CMD=":"
else
  NB_RUN_CMD="qsub -n $nb_nnodes
                   -q $nb_queue
                   -t $nb_time
                   -A $nb_project"
fi
