#!/bin/sh

#-------------------------------------------------------------------------------
# Set default values for compilation
#-------------------------------------------------------------------------------
: ${nb_fc:="ftn"}
: ${nb_cc:="cc"}
: ${nb_fflags:=}
: ${nb_cflags:=}
: ${nb_usr_lflags:=}

#-------------------------------------------------------------------------------
# Submission parameters
#-------------------------------------------------------------------------------
: ${nb_np:=64}
: ${nb_ppn:=64}
: ${nb_project:="GasJetsCylPrio_tesp"}
: ${nb_queue:="default"}
: ${nb_time:=60}

#-------------------------------------------------------------------------------
# Build the submit command for the machine
#-------------------------------------------------------------------------------
function theta_submit() {
  local nb_casename=$1
  local nb_tag=$2
  local nb_np=$3
  local nb_ppn=$4

  local nb_nnodes=$(( nb_np/nb_ppn ))
  local NB_SUBMIT_CMD=""

  if [ $nb_nnodes -le 4 ]; then
    nb_queue=debug-flat-quad
  fi
  
  if [ $nb_nnodes = 0 ]; then
    NB_SUBMIT_CMD=":"
  else
    NB_SUBMIT_CMD="qsub -n $nb_nnodes
                     -q $nb_queue
                     -t $nb_time
                     -A $nb_project"
  fi

  ${NB_SUBMIT_CMD} ${NB_JOBS_DIR}/${nb_machine}.submit $1 $2 $3 $4
}
